apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: client-gateway
  name: client-gateway
spec:
  ports:
  - name: "4010"
    port: 4010
    protocol: TCP
    targetPort: 4010
  selector:
    app: client-gateway
  type: NodePort
status:
  loadBalancer: {}
