apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: payments-ms
  name: payments-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payments-ms
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/store-ms-431319/store-repository/payments-ms
        name: payments-ms
        env:
          - name: PORT
            value: "4010"
          - name: NATS_SERVERS
            value: "nats://nats"
          - name: STRIPE_SUCCESS_URL
            value: "http://localhost:4011/api/payments/stripe-success"
          - name: STRIPE_CANCEL_URL
            value: "http://localhost:4011/api/payments/stripe-cancel"
          - name: STRIPE_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: payments-secrets
                key: stripe_secret_key
          - name: STRIPE_ENDPOINT_SECRET
            valueFrom:
              secretKeyRef:
                name: payments-secrets
                key: stripe_endpoint_secret_key
        resources: {}
status: {}
