apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: payments-service
  name: payments-service
spec:
  ports:
  - name: "4010"
    port: 4010
    protocol: TCP
    targetPort: 4010
  selector:
    app: payments-service
  type: NodePort
status:
  loadBalancer: {}
